### ISSUE TITLE
Add plugins to the action runner

### ISSUE THREAD

**Issue by iVegas** [drupal-ckeditor-libraries-group/actions_runner#11]
Steps to add a new plugin:
- [Create a new repo](/organizations/drupal-ckeditor-libraries-group/repositories/new);
- Set standardized repo name `CKEditor 4 <plugin_label> plugin for Drupal projects`. Get plugin label from the related plugin page `https://ckeditor.com/cke4/addon/<plugin_name>`;
- Add entry to the [action runner script](/drupal-ckeditor-libraries-group/actions_runner/blob/master/.github/workflows/manual.yml#L18);
- Run the `action_script` to import the project.
- [Create a package at Packagist](https://packagist.org/packages/submit);
- Add webhook configuration for the new repo;

[List of the plugins](/ckeditor/ckeditor4/tree/major/plugins):
- [x] [a11yhelp](/drupal-ckeditor-libraries-group/a11yhelp)
- [x] [about](/drupal-ckeditor-libraries-group/about)
- [x] [adobeair](/drupal-ckeditor-libraries-group/adobeair)
- [x] [ajax](/drupal-ckeditor-libraries-group/ajax)
- [x] [autocomplete](/drupal-ckeditor-libraries-group/autocomplete)
- [x] [autoembed](/drupal-ckeditor-libraries-group/autoembed)
- [x] [autogrow](/drupal-ckeditor-libraries-group/autogrow)
- [x] [autolink](/drupal-ckeditor-libraries-group/autolink)
- [x] [balloonpanel](/drupal-ckeditor-libraries-group/balloonpanel)
- [x] balloontoolbar
- [x] basicstyles
- [x] bbcode
- [x] bidi
- [x] blockquote
- [x] button
- [x] clipboard
- [x] cloudservices
- [x] [codesnippet](/drupal-ckeditor-libraries-group/codesnippet)
- [x] codesnippetgeshi
- [x] [colorbutton](/drupal-ckeditor-libraries-group/colorbutton)
- [x] colordialog
- [x] contextmenu
- [x] copyformatting
- [x] devtools
- [x] dialog
- [x] dialogadvtab
- [x] dialogui
- [x] div
- [x] divarea
- [x] docprops
- [x] easyimage
- [x] elementspath
- [x] embed
- [x] embedbase
- [x] embedsemantic
- [x] emoji
- [x] enterkey
- [x] entities
- [x] [fakeobjects](/drupal-ckeditor-libraries-group/fakeobjects)
- [x] filebrowser
- [x] filetools
- [x] [find](drupal-ckeditor-libraries-group/find)
- [x] flash
- [x] floatingspace
- [x] floatpanel
- [x] [font](/drupal-ckeditor-libraries-group/font)
- [x] format
- [x] forms
- [x] horizontalrule
- [x] htmlwriter
- [x] iframe
- [x] iframedialog
- [x] image
- [x] image2
- [x] imagebase
- [x] indent
- [x] indentblock
- [x] indentlist
- [x] justify
- [x] language
- [x] lineutils
- [x] link
- [x] list
- [x] listblock
- [x] liststyle
- [x] magicline
- [x] mathjax
- [x] maximize
- [x] mentions
- [x] menu
- [x] menubutton
- [x] newpage
- [x] [notification](/drupal-ckeditor-libraries-group/notification)
- [x] notificationaggregator
- [x] pagebreak
- [x] panel
- [x] [panelbutton](/drupal-ckeditor-libraries-group/panelbutton)
- [x] pastefromgdocs
- [x] pastefromlibreoffice
- [x] pastefromword
- [x] pastetext
- [x] pastetools
- [x] placeholder
- [x] popup
- [x] preview
- [x] print
- [x] removeformat
- [x] resize
- [x] richcombo
- [x] save
- [x] selectall
- [x] sharedspace
- [x] showblocks
- [x] showborders
- [x] smiley
- [x] sourcearea
- [x] sourcedialog
- [x] specialchar
- [x] stylescombo
- [x] stylesheetparser
- [x] tab
- [x] table
- [x] tableresize
- [x] tableselection
- [x] tabletools
- [x] [templates](/drupal-ckeditor-libraries-group/templates)
- [x] [textmatch](/drupal-ckeditor-libraries-group/textmatch)
- [x] [textwatcher](/drupal-ckeditor-libraries-group/textwatcher)
- [x] toolbar
- [x] uicolor
- [x] undo
- [x] uploadfile
- [x] uploadimage
- [x] uploadwidget
- [x] widget
- [x] widgetselection
- [x] wysiwygarea
- [x] [xml](/drupal-ckeditor-libraries-group/xml)

**Comment by sembrat** [comment]
Thanks for writing this up - looks perfect! Copied this into https://github.com/drupal-ckeditor-libraries-group/actions_runner/wiki/Plugin-Management as well, just to be safe.

**Comment by sembrat** [comment]
Updated the playbook directions, as packagist requires the library have a composer.json, which means adding to packagist would need to happen after the action_runner.

**Comment by iVegas** [comment]
I recommend performing running the actions as little as possible because of the limited free action minutes limit.
Let's say perform 10-20 times steps for new plugins while skipping action performing steps and then perform action runner for those newly added plugins just once.

**Comment by sembrat** [comment]
Good call, @iVegas . I'll be more deliberate on those schedulings to save our free action minutes. Thanks for flagging this!

**Comment by iVegas** [comment]
Resolved by #20
