### ISSUE TITLE
Add external plugins to the actions_runner

### ISSUE THREAD

**Issue by sembrat** [drupal-ckeditor-libraries-group/actions_runner#16]
Steps to add a new plugin:
- [Create a new repo](/organizations/drupal-ckeditor-libraries-group/repositories/new);
- Set standardized repo name `Contributed CKEditor 4 <plugin_label> plugin for Drupal projects`. Get plugin label from the project `plugin.js`.
- Add entry to the [action runner script](/drupal-ckeditor-libraries-group/actions_runner/blob/master/.github/workflows/manual.yml#L18);
- Run the `action_script` to import the project.
- [Create a package at Packagist](https://packagist.org/packages/submit);
- Add webhook configuration for the new repo;

List of the plugins:

- [x] [format_buttons](https://github.com/stevenvdhout/format_buttons)
- [x] [wordcount](https://github.com/w8tcha/CKEditor-WordCount-Plugin)
- [x] [youtube](https://github.com/fonini/ckeditor-youtube-plugin)

**Comment by sembrat** [comment]
The three original plugins requested have been added to the actions_runner workflow.

**Comment by iVegas** [comment]
Looks as done for me. Now the runner takes care about repo and package creation. See #20
